default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: postgres #""
 password: 1234 #""

development:
 <<: *default
 database: zgloska_development

production:
 primary: &primary_production
  <<: *default
  database: zgloska_production
  username: zgloska
  password: <%= ENV["ZGLOSKA_DATABASE_PASSWORD"] %>
 cache:
  <<: *primary_production
  database: zgloska_production_cache
  migrations_paths: db/cache_migrate
 queue:
  <<: *primary_production
  database: zgloska_production_queue
  migrations_paths: db/queue_migrate
 cable:
  <<: *primary_production
  database: zgloska_production_cable
  migrations_paths: db/cable_migrate
