default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: postgres
 password: 1234

development:
 <<: *default
 database: zgloska_development

test:
 <<: *default
 database: zgloska_test

production:
 url: <%= ENV["DATABASE_URL"] %>
